apiVersion: apps/v1
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonar-service
  name: sonar-service
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
      nodePort: 30299
  selector:
    app: sonar-service
  type: NodePort